version: '2.3'
services:
  aggregator:
    image: escalon/microfrontends-aggregator:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
  orderservice:
    image: escalon/microfrontends-order-service:0.0.1-SNAPSHOT
    ports:
      - "8088:8088"
  zuulservice:
    image: escalon/microfrontends-zuul-service:latest
    ports:
      - "8888:8888"
  cart:
    image: escalon/microfrontends-cart:latest
    ports:
      - "3005:3005"
  product:
    image: escalon/microfrontends-product:latest
    ports:
      - "3006:3006"
